### ISSUE TITLE
Encryption and Upload

### ISSUE THREAD

**Issue by Deepnerd** [Marineeee/FileUploader-Simple-Securised#1]
This is not an issue but a request.

1) How to set my download links smaller? i mean how to reduce generateRandomString character length? when i was upload some files that link character length is more than 100. i need that to be 30 to 40 length.

2) And also can you add an loading bar progress in file uploading. when some file uploading it's shows uploading progress.  that will be awesome! you can find cool ideas from codepen.io :) just saying.

3) Can you just add Browse Files for the same UPLOAD button? like anonfiles did.

4) Also when the file uploaded the link should be shows with copy to clipboard function. 

5) How to increase upload limit?

i hope you'll update this soon as possible. your coding skills are neat! Thank you!

**Comment by cypherbits** [comment]
Hi @Deepnerd, I have more questions about this repo:

- Why encrypt the directory name and not using a simple hash? (Put a random string on the download URL and the directory is a sha256 hash of that string for example)

- Encryption confusion: we are not encrypting any files here... they are stored in plain text.

**Comment by Deepnerd** [comment]
Hi @cypherbits Yeah, but the repo owner is inactive, i really don't know how to fix these because i have 0 coding skills. im looking for someone to fix this code to a secure one. i really looking for script like anonfiles.com . need to be simple and light. thanks for the info mate. i really didn't know that this script don't encrypt any files.

**Comment by Ross1337** [comment]
Hello guys, as said this repo is inactive since few time ! That was a simple project, if you need to modify something you should learn how to do php before (sorry for the response time lol)
